name: bjit_education
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # utility packages
  flutter_native_splash: ^2.3.5
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  cached_network_image: ^3.3.0
  modal_progress_hud_nsn: ^0.4.0
  image_picker: ^1.0.4
  bloc:
  flutter_bloc:
  equatable:
  shared_preferences: ^2.0.15
  get_it: ^7.6.0

  # this package will remove later
  dots_indicator: ^2.1.1

  retrofit: '>=4.0.0 <5.0.0'
  flutter_hooks: ^0.18.3

  floor: ^1.4.2
  path_provider: ^2.1.1

  flutter_svg: ^1.1.6
#--------------- ./ PACKAGE END -----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  json_serializable: ^6.3.1
  retrofit_generator: '>=5.0.0 < 6.0.0'
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1

flutter:
  uses-material-design: true

#------------ LOCAL ASSETS ------------#
  assets:
      - assets/
      - assets/images/
#------------- local assets end -----------#


#------------ local fonts -----------------#
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

    - family: Squada One
      fonts:
        - asset: assets/fonts/SquadaOneRegular.ttf
          weight: 400
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
    - family: Archivo
      fonts:
        - asset: assets/fonts/ArchivoRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ArchivoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/ArchivoRomanBold.ttf
          weight: 700
    - family: Oleo Script
      fonts:
        - asset: assets/fonts/OleoScriptRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
    - family: Anton
      fonts:
        - asset: assets/fonts/AntonRegular.ttf
          weight: 400
    - family: Alfa Slab One
      fonts:
        - asset: assets/fonts/AlfaSlabOneRegular.ttf
          weight: 400

#------------ local fonts end-----------------#
